Update README.md
codecov/example-ruby pull request #4
Opened 2018-01-16 19:29 UTC by TomPed

From my view I don't see how we are uploading the reports. But what we are adding the the `Gemfile` might do this, I'm not familiar with ruby, let me know!

2018-01-17 12:08 UTC, stevepeak commented
Ruby is different. You must use the Codecov Ruby gem: https://github.com/codecov/codecov-ruby

2018-01-17 15:22 UTC, TomPed commented
Updated private repo section.

2018-02-01 10:13 UTC, brntbeer commented
@TomPed can you update the OP (original post) here with what the goals / objectives of this PR are? I just wanna help out in any way i can!

2018-02-01 16:35 UTC, TomPed commented
Updated 😄.

2018-02-01 17:09 UTC, brntbeer requested changes
@TomPed overall i love the change this readme is taking to be more similar to other example repositories.

I think there's some strength in the README showing how to use the ruby library itself, but it may also benefit from a challenge to the reader to do something like "Fork this repo and achieve 100%!" by having them add the test themselves AND get exposed to seeing the integration in action! Just a thought though, I'm happy to do that as a follow up PR myself 😄 :octocat:

2018-02-01 17:09 UTC, brntbeer commented on README.md
> +### Travis Setup
@TomPed To make this a bit more agnostic, what if we just made this an `##` and title it "CI setup" and add a  descriptive line of text mentioning that this is for travis CI but that most modern CIs with a `.yml` file should work appropriately. potentially linking to additional popular CI services like CircleCI and Jenkins.

additionally, i would removed the line "guide" above it, i think? It should be implicitly understood this is a guide from reading it, in my opinion

2018-02-01 17:09 UTC, brntbeer commented on README.md
> +### Produce Coverage Reports
IMO this section is what confuses me the most between this repo and https://github.com/codecov/codecov-ruby. 

@TomPed what are your thoughts on changing this title to be "How this repo produces coverage reports" ?

2020-08-04 19:54 UTC, thomasrockhu commented
Closing in favor of https://github.com/codecov/example-ruby/pull/10

2020-08-04 19:54 UTC, closed without merging